language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
  - CI=true  
deploy:
  provider: heroku
  api_key:
    secure: HyT2H/zWDfiagZPl/XJZVqie46foYUkONQ9JiOdzjBtBVMtl8C0uxxf7FAcsaoUXx8atCCMgrwZpAZr8qESoeVAQPWoJBm6D+mYe8bn6bUhI/e/XUOzt6qZd2r8dTTmL9Gt1sWTpAG208EfPtiKchslivhWefRvrTVn3rHextPPTX8am3D/y2Nd/PcUyvm44GG0AtS4i2kJscGup9K2GsjRRTbbGPKJs3N0/nYe8AUIF2hR/2oRy+V1J+HPmjfGsnpUMsJhGYHEXquqLtNHISKLJUVYTQaPPw3QiiYvpiqzsDLFdZDn2S6xpvjQHXqLE41NxJo+s4LfRV5SzTWrIdoTusEVRQs8tqaVb5bv+bLT3jaZQriuDZnINAO5uXsr/ZQT0aUK1uUOswAkDiwJuHJeyHc2AX8Ut6HUt7BURwEtXUFNU4vYgMxUgboRDw/tVHgU4B7vS9UOkaicodUUX6B3E9srY9FPVqdZupB/4HCu0bH7GP1gh+cp7Um09ePldHfyJuSsyuRKHW3MZaOUSwzWKMrVOCJfBKiJp0O3GRb6Lj3MM9zAqvKpMny6mCGGPJbTTdYplCtd7AZGgWCUM8wp8iByo9+v97wVGpiv7c3bUBULL7ZPjq7gr/rYPVqDsig4i71Z1zN9jxhJ9fHTgLeyQPd3JBqrqp1YkeZfwprQ=
  app: blooming-badlands-62899
  on:
    repo: alexmanzo/movie-search



